import fs from "fs";
import path from "path";
import { type ServiceConfig } from "../src/config";
import {
  generateCaddy,
  renderCaddyLabels,
  renderCaddyfile,
  renderComposeOverride,
} from "../src/caddy";
import {
  captureConsole,
  makeTempDir,
  read,
  removeTempDir,
  settingsFor,
  writeFile,
  type ConsoleCapture,
  type TestConfig,
} from "./helpers";

const services: ServiceConfig[] = [
  { route: "jellyfin", target: "http://localhost:8096" },
  { route: "photos", target: "http://localhost:2283", domains: ["photos.example.org"] },
];
const config: TestConfig = { domain: "example.com", services };
const UPSTREAM = "host.docker.internal:8080";
const DEFAULT_NOTE = ' (default — set "caddyUpstream" in config.json to change)';
const HEADER = "# Generated by DockerWakeUp (proxy-generator) from config.json — re-running the\n";

describe("renderCaddyfile", () => {
  it("renders the header and one block per site", () => {
    const text = renderCaddyfile({
      configName: "config.json",
      caddyfilePath: "/srv/pg/Caddyfile",
      upstream: UPSTREAM,
      sites: [
        { address: "jellyfin.example.com", customLines: ["\tbasicauth {", "\t}"] },
        { address: "photos.example.com, photos.example.org", customLines: [] },
      ],
    });
    expect(text).toBe(
      [
        "# Generated by DockerWakeUp (proxy-generator) from config.json — re-running the",
        "# generator overwrites this file except for the custom-start/custom-end regions.",
        "# Add a comment line saying wakeup:manual to take the file out of the generator's hands.",
        "#",
        "# Plain Caddy:          import /srv/pg/Caddyfile",
        "# caddy-docker-proxy:   mount this file and set CADDY_DOCKER_CADDYFILE_PATH to it",
        "",
        "jellyfin.example.com {",
        "\t# custom-start (lines between these markers survive regeneration)",
        "\tbasicauth {",
        "\t}",
        "\t# custom-end",
        "",
        "\t# The wake proxy routes by hostname; Caddy adds X-Forwarded-For/-Proto/-Host",
        "\t# and passes WebSockets and SSE through as-is.",
        "\treverse_proxy host.docker.internal:8080",
        "}",
        "",
        "photos.example.com, photos.example.org {",
        "\t# custom-start (lines between these markers survive regeneration)",
        "\t# custom-end",
        "",
        "\t# The wake proxy routes by hostname; Caddy adds X-Forwarded-For/-Proto/-Host",
        "\t# and passes WebSockets and SSE through as-is.",
        "\treverse_proxy host.docker.internal:8080",
        "}",
        "",
      ].join("\n"),
    );
  });

  it("renders just the header without sites", () => {
    const text = renderCaddyfile({
      configName: "config.json",
      caddyfilePath: "/srv/pg/Caddyfile",
      upstream: UPSTREAM,
      sites: [],
    });
    expect(text.endsWith("CADDY_DOCKER_CADDYFILE_PATH to it\n\n\n")).toBe(true);
    expect(text).not.toContain("reverse_proxy");
  });
});

describe("renderCaddyLabels", () => {
  it("numbers the labels in service order", () => {
    expect(
      renderCaddyLabels(
        ["jellyfin.example.com", "photos.example.com photos.example.org"],
        UPSTREAM,
      ),
    ).toBe(
      '      caddy_0: "jellyfin.example.com"\n' +
        '      caddy_0.reverse_proxy: "host.docker.internal:8080"\n' +
        '      caddy_1: "photos.example.com photos.example.org"\n' +
        '      caddy_1.reverse_proxy: "host.docker.internal:8080"\n',
    );
  });

  it("renders an empty mapping without services", () => {
    expect(renderCaddyLabels([], UPSTREAM)).toBe("      {}\n");
  });

  it("quotes values as YAML double-quoted scalars", () => {
    expect(renderCaddyLabels(['a"b'], "x")).toBe(
      '      caddy_0: "a\\"b"\n      caddy_0.reverse_proxy: "x"\n',
    );
  });
});

describe("renderComposeOverride", () => {
  it("renders the labels around the custom region", () => {
    expect(
      renderComposeOverride({
        configName: "config.json",
        upstream: UPSTREAM,
        hostLists: ["jellyfin.example.com"],
        customLines: ['      caddy.email: "admin@example.com"'],
      }),
    ).toBe(
      [
        "# Generated by DockerWakeUp (proxy-generator) from config.json — re-running the",
        "# generator overwrites this file except for the custom-start/custom-end region.",
        "# Add a comment line saying wakeup:manual to take the file out of the generator's hands.",
        "#",
        "# Adds caddy-docker-proxy labels to the docker-wakeup container. Docker Compose",
        "# loads this override automatically next to docker-compose.yml, so a plain",
        "#",
        "#   docker compose up -d --build",
        "#",
        "# includes the labels. The labels point Caddy at host.docker.internal:8080; the Caddy",
        "# container must be able to reach the wake proxy on the host (see",
        "# examples/caddy-docker-proxy.yml). Not using Caddy? Just delete this file.",
        "services:",
        "  docker-wakeup:",
        "    labels:",
        "      # custom-start (lines between these markers survive regeneration)",
        '      caddy.email: "admin@example.com"',
        "      # custom-end",
        '      caddy_0: "jellyfin.example.com"',
        '      caddy_0.reverse_proxy: "host.docker.internal:8080"',
        "",
      ].join("\n"),
    );
  });
});

describe("generateCaddy", () => {
  let root: string;
  let generatorDir: string;
  let caddyfilePath: string;
  let composePath: string;
  let out: ConsoleCapture;

  beforeEach(() => {
    root = makeTempDir();
    generatorDir = path.join(root, "proxy-generator");
    fs.mkdirSync(generatorDir);
    caddyfilePath = path.join(generatorDir, "Caddyfile");
    composePath = path.join(root, "docker-compose.override.yml");
    out = captureConsole();
  });
  afterEach(() => removeTempDir(root));

  const run = (cfg = config, caddyfileOnly?: boolean, configPath?: string) =>
    generateCaddy(settingsFor(cfg, configPath), { generatorDir }, caddyfileOnly);
  const freshCaddyfile = (upstream = UPSTREAM) =>
    renderCaddyfile({
      configName: "config.json",
      caddyfilePath,
      upstream,
      sites: [
        { address: "jellyfin.example.com", customLines: [] },
        { address: "photos.example.com, photos.example.org", customLines: [] },
      ],
    });
  const freshOverride = (upstream = UPSTREAM, customLines: string[] = []) =>
    renderComposeOverride({
      configName: "config.json",
      upstream,
      hostLists: ["jellyfin.example.com", "photos.example.com photos.example.org"],
      customLines,
    });

  it("writes the Caddyfile and the compose override from scratch", () => {
    run();
    expect(read(caddyfilePath)).toBe(freshCaddyfile());
    expect(read(composePath)).toBe(freshOverride());
    expect(out.log).toEqual([
      `Generated: ${caddyfilePath} (2 site block(s))`,
      `Generated: ${composePath} (2 site(s))`,
      `\nUpstream for Caddy: ${UPSTREAM}${DEFAULT_NOTE}`,
    ]);
    expect(out.warn).toEqual([]);
    expect(out.error).toEqual([]);
  });

  it("derives the default upstream from the proxy port", () => {
    run({ ...config, proxyPort: 9090 });
    expect(read(caddyfilePath)).toBe(freshCaddyfile("host.docker.internal:9090"));
    expect(out.log[2]).toBe(`\nUpstream for Caddy: host.docker.internal:9090${DEFAULT_NOTE}`);
  });

  it("uses the configured upstream without the default hint", () => {
    run({ ...config, caddyUpstream: "127.0.0.1:8080" });
    expect(read(caddyfilePath)).toBe(freshCaddyfile("127.0.0.1:8080"));
    expect(read(composePath)).toBe(freshOverride("127.0.0.1:8080"));
    expect(out.log[2]).toBe("\nUpstream for Caddy: 127.0.0.1:8080");
  });

  it("names the config file in both headers", () => {
    run(config, false, "/etc/wakeup/my-config.json");
    const header =
      "# Generated by DockerWakeUp (proxy-generator) from my-config.json — re-running the\n";
    expect(read(caddyfilePath).startsWith(header)).toBe(true);
    expect(read(composePath).startsWith(header)).toBe(true);
  });

  it("carries each site's custom lines over into the regenerated Caddyfile", () => {
    writeFile(
      caddyfilePath,
      renderCaddyfile({
        configName: "old.json",
        caddyfilePath: "/elsewhere/Caddyfile",
        upstream: "old:1",
        sites: [
          { address: "jellyfin.example.com", customLines: [] },
          { address: "photos.example.com, photos.example.org", customLines: ["\tencode gzip"] },
        ],
      }),
    );
    run();
    expect(out.log[0]).toBe(
      "Preserving 1 custom line(s) for photos.example.com, photos.example.org",
    );
    expect(read(caddyfilePath)).toBe(
      renderCaddyfile({
        configName: "config.json",
        caddyfilePath,
        upstream: UPSTREAM,
        sites: [
          { address: "jellyfin.example.com", customLines: [] },
          { address: "photos.example.com, photos.example.org", customLines: ["\tencode gzip"] },
        ],
      }),
    );
  });

  it("drops custom lines whose site address changed", () => {
    writeFile(
      caddyfilePath,
      renderCaddyfile({
        configName: "config.json",
        caddyfilePath,
        upstream: UPSTREAM,
        sites: [{ address: "photos.example.com", customLines: ["\tencode gzip"] }],
      }),
    );
    run();
    expect(read(caddyfilePath)).toBe(freshCaddyfile());
    expect(out.log.filter((line) => line.startsWith("Preserving"))).toEqual([]);
  });

  it("keeps a Caddyfile carrying the manual marker and still writes the override", () => {
    writeFile(caddyfilePath, "# wakeup:manual\nexample.com {\n}\n");
    run();
    expect(read(caddyfilePath)).toBe("# wakeup:manual\nexample.com {\n}\n");
    expect(read(composePath)).toBe(freshOverride());
    expect(out.log).toEqual([
      `Kept as-is (# wakeup:manual): ${caddyfilePath}`,
      `Generated: ${composePath} (2 site(s))`,
      `\nUpstream for Caddy: ${UPSTREAM}${DEFAULT_NOTE}`,
    ]);
  });

  it("keeps the custom label lines of its own override", () => {
    writeFile(composePath, freshOverride("old:1", ['      caddy.email: "admin@example.com"']));
    run();
    expect(out.log[1]).toBe("Preserving 1 custom label line(s) in docker-compose.override.yml");
    expect(read(composePath)).toBe(
      freshOverride(UPSTREAM, ['      caddy.email: "admin@example.com"']),
    );
  });

  it("keeps an override carrying the manual marker", () => {
    writeFile(composePath, `${HEADER}# wakeup:manual\nservices: {}\n`);
    run();
    expect(read(composePath)).toBe(`${HEADER}# wakeup:manual\nservices: {}\n`);
    expect(out.log[1]).toBe(`Kept as-is (# wakeup:manual): ${composePath}`);
  });

  it("leaves a foreign override untouched and shows the labels to merge", () => {
    writeFile(composePath, "services:\n  docker-wakeup:\n    volumes: []\n");
    run();
    expect(read(composePath)).toBe("services:\n  docker-wakeup:\n    volumes: []\n");
    expect(out.warn).toEqual([
      `\n${composePath} exists and was not written by this generator — left untouched.\n` +
        "Add these labels to its docker-wakeup service yourself:\n\n" +
        "services:\n  docker-wakeup:\n    labels:\n" +
        '      caddy_0: "jellyfin.example.com"\n' +
        '      caddy_0.reverse_proxy: "host.docker.internal:8080"\n' +
        '      caddy_1: "photos.example.com photos.example.org"\n' +
        '      caddy_1.reverse_proxy: "host.docker.internal:8080"\n',
    ]);
    expect(out.log).toEqual([
      `Generated: ${caddyfilePath} (2 site block(s))`,
      `\nUpstream for Caddy: ${UPSTREAM}${DEFAULT_NOTE}`,
    ]);
  });

  it("skips the override with --caddyfile-only", () => {
    run(config, true);
    expect(fs.existsSync(composePath)).toBe(false);
    expect(read(caddyfilePath)).toBe(freshCaddyfile());
    expect(out.log).toEqual([
      `Generated: ${caddyfilePath} (2 site block(s))`,
      "Skipped docker-compose.override.yml (--caddyfile-only)",
      `\nUpstream for Caddy: ${UPSTREAM}${DEFAULT_NOTE}`,
    ]);
  });

  it("writes an empty label mapping and no site blocks without HTTP services", () => {
    run({ domain: "example.com", services: [{ route: "mc", target: "x:1", type: "tcp" }] });
    expect(read(caddyfilePath)).toBe(
      renderCaddyfile({ configName: "config.json", caddyfilePath, upstream: UPSTREAM, sites: [] }),
    );
    expect(read(composePath)).toBe(
      renderComposeOverride({
        configName: "config.json",
        upstream: UPSTREAM,
        hostLists: [],
        customLines: [],
      }),
    );
    expect(read(composePath).endsWith("      # custom-end\n      {}\n")).toBe(true);
    expect(out.log).toEqual([
      `Generated: ${caddyfilePath} (0 site block(s))`,
      `Generated: ${composePath} (0 site(s))`,
      `\nUpstream for Caddy: ${UPSTREAM}${DEFAULT_NOTE}`,
    ]);
  });
});
