import {
  CUSTOM_END,
  CUSTOM_START,
  GENERATED_HEADER,
  MANUAL_MARKER,
  extractCaddyfileCustomLines,
  extractCustomLines,
} from "../src/markers";

describe("marker constants", () => {
  it("are the strings the generated files and their docs use", () => {
    expect(MANUAL_MARKER).toBe("# wakeup:manual");
    expect(CUSTOM_START).toBe("# custom-start");
    expect(CUSTOM_END).toBe("# custom-end");
    expect(GENERATED_HEADER).toBe("# Generated by DockerWakeUp (proxy-generator)");
  });
});

describe("extractCustomLines", () => {
  it("returns the lines between the first custom-start/custom-end pair, untouched", () => {
    const text = [
      "server {",
      "    # custom-start (lines between these markers survive regeneration)",
      '    auth_basic "Restricted";',
      "",
      "    auth_basic_user_file /etc/nginx/.htpasswd;",
      "    # custom-end",
      "}",
    ].join("\n");
    expect(extractCustomLines(text)).toEqual([
      '    auth_basic "Restricted";',
      "",
      "    auth_basic_user_file /etc/nginx/.htpasswd;",
    ]);
  });

  it("returns [] for text without markers", () => {
    expect(extractCustomLines("")).toEqual([]);
    expect(extractCustomLines("server {\n}\n")).toEqual([]);
  });

  it("returns [] when only one of the markers is present", () => {
    expect(extractCustomLines("# custom-start\nfoo\n")).toEqual([]);
    expect(extractCustomLines("foo\n# custom-end\n")).toEqual([]);
  });

  it("returns [] when the markers are adjacent", () => {
    expect(extractCustomLines("# custom-start\n# custom-end\n")).toEqual([]);
  });

  it("returns [] when custom-end comes before custom-start", () => {
    expect(extractCustomLines("# custom-end\nfoo\n# custom-start\n")).toEqual([]);
  });

  it("gives up when a stray custom-end precedes the real region", () => {
    // findIndex takes the first custom-end, so the later pair is never seen
    expect(extractCustomLines("# custom-end\n# custom-start\nfoo\n# custom-end\n")).toEqual([]);
  });

  it("only looks at the first pair", () => {
    const text = "# custom-start\none\n# custom-end\n# custom-start\ntwo\n# custom-end\n";
    expect(extractCustomLines(text)).toEqual(["one"]);
  });

  it("recognises markers embedded anywhere in a line", () => {
    const text = "\t# custom-start (note)\n\tline\n      # custom-end trailing\n";
    expect(extractCustomLines(text)).toEqual(["\tline"]);
  });
});

describe("extractCaddyfileCustomLines", () => {
  it("returns an empty map for an empty file", () => {
    expect(extractCaddyfileCustomLines("")).toEqual(new Map());
  });

  it("collects each site block's custom lines under its address", () => {
    const text = [
      "# Generated by DockerWakeUp (proxy-generator) from config.json",
      "",
      "jellyfin.example.com {",
      "\t# custom-start (lines between these markers survive regeneration)",
      "\tbasicauth {",
      "\t\tbob $2a$14$hash",
      "\t}",
      "\t# custom-end",
      "\treverse_proxy host.docker.internal:8080",
      "}",
      "",
      "photos.example.com, pics.example.net {",
      "\t# custom-start (lines between these markers survive regeneration)",
      "\theader X-Robots-Tag none",
      "\t# custom-end",
      "\treverse_proxy host.docker.internal:8080",
      "}",
      "",
    ].join("\n");
    expect(extractCaddyfileCustomLines(text)).toEqual(
      new Map([
        ["jellyfin.example.com", ["\tbasicauth {", "\t\tbob $2a$14$hash", "\t}"]],
        ["photos.example.com, pics.example.net", ["\theader X-Robots-Tag none"]],
      ]),
    );
  });

  it("leaves out sites whose custom region is empty", () => {
    const text = "a.example.com {\n\t# custom-start\n\t# custom-end\n}\n";
    expect(extractCaddyfileCustomLines(text)).toEqual(new Map());
  });

  it("leaves out custom lines that appear before any site address", () => {
    const text = "# custom-start\nglobal\n# custom-end\na.example.com {\n}\n";
    expect(extractCaddyfileCustomLines(text)).toEqual(new Map());
  });

  it("leaves out an unterminated custom region", () => {
    const text = "a.example.com {\n\t# custom-start\n\tline\n}\n";
    expect(extractCaddyfileCustomLines(text)).toEqual(new Map());
  });

  it("does not mistake comments or indented directive blocks for site addresses", () => {
    const text = [
      "# comment {",
      "a.example.com {",
      "\thandle {",
      "\t}",
      "\t# custom-start",
      "\tline",
      "\t# custom-end",
      "}",
    ].join("\n");
    expect(extractCaddyfileCustomLines(text)).toEqual(new Map([["a.example.com", ["\tline"]]]));
  });

  it("trims whitespace around the address", () => {
    const text = "a.example.com, b.example.com   {   \n\t# custom-start\n\tx\n\t# custom-end\n}\n";
    expect(extractCaddyfileCustomLines(text)).toEqual(
      new Map([["a.example.com, b.example.com", ["\tx"]]]),
    );
  });

  it("keeps the last region when an address appears twice", () => {
    const text =
      "a.example.com {\n\t# custom-start\n\tfirst\n\t# custom-end\n}\n" +
      "a.example.com {\n\t# custom-start\n\tsecond\n\t# custom-end\n}\n";
    expect(extractCaddyfileCustomLines(text)).toEqual(new Map([["a.example.com", ["\tsecond"]]]));
  });

  it("treats a nested custom-start as an ordinary custom line", () => {
    const text =
      "a.example.com {\n\t# custom-start\n\t# custom-start again\n\tx\n\t# custom-end\n}\n";
    expect(extractCaddyfileCustomLines(text)).toEqual(
      new Map([["a.example.com", ["\t# custom-start again", "\tx"]]]),
    );
  });
});
