import fs from "fs";
import path from "path";
import { type ServiceConfig } from "../src/config";
import { generateTraefik, renderTraefikConfig, renderTraefikRouters } from "../src/traefik";
import {
  captureConsole,
  makeTempDir,
  read,
  removeTempDir,
  settingsFor,
  writeFile,
  type ConsoleCapture,
  type TestConfig,
} from "./helpers";

const services: ServiceConfig[] = [
  { route: "jellyfin", target: "http://localhost:8096" },
  { route: "photos", target: "http://localhost:2283", domains: ["photos.example.org"] },
];
const config: TestConfig = { domain: "example.com", services };
const DEFAULT_NOTE = ' (default — set "traefikUpstream" in config.json to change)';
const TLS_COMMENT =
  "      # TLS comes from the entrypoint (examples/traefik.yml enables it there);\n" +
  '      # or set "traefikCertResolver" in config.json to add one per router\n';

describe("renderTraefikRouters", () => {
  it("renders the catch-all router and one router per service with extra domains", () => {
    expect(
      renderTraefikRouters({
        domain: "example.com",
        services,
        entrypoint: "websecure",
        certResolver: "letsencrypt",
      }),
    ).toEqual([
      "    docker-wakeup:\n" +
        "      rule: HostRegexp(`^.+\\.example\\.com$`)\n" +
        '      entryPoints: ["websecure"]\n' +
        '      tls: { certResolver: "letsencrypt" }\n' +
        "      service: docker-wakeup\n",
      "    docker-wakeup-photos-aliases:\n" +
        "      rule: Host(`photos.example.org`)\n" +
        '      entryPoints: ["websecure"]\n' +
        '      tls: { certResolver: "letsencrypt" }\n' +
        "      service: docker-wakeup\n",
    ]);
  });

  it("joins several aliases with ||", () => {
    const [, aliases] = renderTraefikRouters({
      domain: "example.com",
      services: [{ route: "a", target: "x", domains: ["a.net", "b.org"] }],
      entrypoint: "websecure",
    });
    expect(aliases).toContain("      rule: Host(`a.net`) || Host(`b.org`)\n");
  });

  it("explains entrypoint TLS when there is no resolver", () => {
    const [catchAll] = renderTraefikRouters({
      domain: "example.com",
      services: [],
      entrypoint: "web",
    });
    expect(catchAll).toBe(
      "    docker-wakeup:\n" +
        "      rule: HostRegexp(`^.+\\.example\\.com$`)\n" +
        '      entryPoints: ["web"]\n' +
        TLS_COMMENT +
        "      service: docker-wakeup\n",
    );
  });

  it("treats an empty resolver as unset", () => {
    const [catchAll] = renderTraefikRouters({
      domain: "example.com",
      services: [],
      entrypoint: "web",
      certResolver: "",
    });
    expect(catchAll).toContain(TLS_COMMENT);
  });

  it("escapes regexp metacharacters in the domain", () => {
    expect(
      renderTraefikRouters({ domain: "my-site.co.uk", services: [], entrypoint: "web" })[0],
    ).toContain("HostRegexp(`^.+\\.my-site\\.co\\.uk$`)");
    expect(
      renderTraefikRouters({ domain: "a+b.(c)", services: [], entrypoint: "web" })[0],
    ).toContain("HostRegexp(`^.+\\.a\\+b\\.\\(c\\)$`)");
  });
});

describe("renderTraefikConfig", () => {
  it("renders the header, the routers and the docker-wakeup service", () => {
    expect(
      renderTraefikConfig({
        configName: "config.json",
        routers: [
          "    r1:\n      service: docker-wakeup\n",
          "    r2:\n      service: docker-wakeup\n",
        ],
        upstream: "host.docker.internal:8080",
      }),
    ).toBe(
      [
        "# Generated by DockerWakeUp (proxy-generator) from config.json — re-running the",
        "# generator overwrites this file. Add a comment line saying wakeup:manual to",
        "# take it out of the generator's hands.",
        "#",
        "# Dynamic configuration for Traefik's file provider. Point Traefik at it:",
        "#   --providers.file.filename=/etc/traefik/docker-wakeup.yml",
        "#   --providers.file.watch=true",
        "# (mount this file there — see examples/traefik.yml for a complete stack.)",
        "# The wake proxy routes by hostname, so this file only changes when the",
        "# domain or per-service domains aliases change.",
        "http:",
        "  routers:",
        "    r1:",
        "      service: docker-wakeup",
        "    r2:",
        "      service: docker-wakeup",
        "  services:",
        "    docker-wakeup:",
        "      loadBalancer:",
        "        servers:",
        '          - url: "http://host.docker.internal:8080"',
        "",
      ].join("\n"),
    );
  });
});

describe("generateTraefik", () => {
  let root: string;
  let generatorDir: string;
  let outPath: string;
  let out: ConsoleCapture;

  beforeEach(() => {
    root = makeTempDir();
    generatorDir = path.join(root, "proxy-generator");
    fs.mkdirSync(generatorDir);
    outPath = path.join(generatorDir, "traefik-dynamic.yml");
    out = captureConsole();
  });
  afterEach(() => removeTempDir(root));

  const run = (cfg = config) => generateTraefik(settingsFor(cfg), { generatorDir });

  it("writes traefik-dynamic.yml with the default entrypoint and upstream", () => {
    run();
    expect(read(outPath)).toBe(
      renderTraefikConfig({
        configName: "config.json",
        routers: renderTraefikRouters({ domain: "example.com", services, entrypoint: "websecure" }),
        upstream: "host.docker.internal:8080",
      }),
    );
    expect(out.log).toEqual([
      `Generated: ${outPath} (catch-all *.example.com + 1 alias router(s))`,
      `\nUpstream for Traefik: http://host.docker.internal:8080${DEFAULT_NOTE}`,
    ]);
    expect(out.warn).toEqual([]);
    expect(out.error).toEqual([]);
  });

  it("omits the alias count when no service has extra domains", () => {
    run({ ...config, services: [services[0]], proxyPort: 9090 });
    expect(read(outPath)).toContain('          - url: "http://host.docker.internal:9090"\n');
    expect(read(outPath)).not.toContain("-aliases:");
    expect(out.log[0]).toBe(`Generated: ${outPath} (catch-all *.example.com)`);
  });

  it("uses the configured entrypoint, upstream and certResolver", () => {
    run({
      ...config,
      traefikEntrypoint: "web",
      traefikUpstream: "127.0.0.1:8080",
      traefikCertResolver: "letsencrypt",
    });
    const text = read(outPath);
    expect(text).toContain('      entryPoints: ["web"]\n');
    expect(text).toContain('      tls: { certResolver: "letsencrypt" }\n');
    expect(text).not.toContain(TLS_COMMENT);
    expect(text).toContain('          - url: "http://127.0.0.1:8080"\n');
    expect(out.log[1]).toBe("\nUpstream for Traefik: http://127.0.0.1:8080");
  });

  it("keeps a file carrying the manual marker", () => {
    writeFile(outPath, "# wakeup:manual\nhttp: {}\n");
    run();
    expect(read(outPath)).toBe("# wakeup:manual\nhttp: {}\n");
    expect(out.log).toEqual([`Kept as-is (# wakeup:manual): ${outPath}`]);
  });

  it("overwrites an existing generated file", () => {
    writeFile(outPath, "# Generated by DockerWakeUp (proxy-generator) from old.json\nhttp: {}\n");
    run();
    expect(read(outPath)).toContain("    docker-wakeup-photos-aliases:\n");
    expect(out.log[0]).toBe(`Generated: ${outPath} (catch-all *.example.com + 1 alias router(s))`);
  });
});
