import fs from "fs";
import path from "path";

// Generates Caddy configuration for the HTTP services in config.json:
//
//   Caddyfile                 one site block per service. Use it with a plain
//                             Caddy install (`import` it from your Caddyfile)
//                             or hand it to caddy-docker-proxy as the base
//                             Caddyfile (CADDY_DOCKER_CADDYFILE_PATH).
//   ../docker-compose.override.yml
//                             compose override (auto-loaded by docker compose
//                             next to docker-compose.yml) that puts
//                             caddy-docker-proxy labels on the docker-wakeup
//                             container, for people who run DockerWakeUp
//                             itself with Docker.
//
// Usage: npm run generate [-- /path/to/config.json] [--caddyfile-only]
//    or: docker compose run --rm caddy-generator   (no Node.js on the host)
//
// --caddyfile-only skips docker-compose.override.yml (used by setup-service.sh:
// SystemD/PM2 deployments have no docker-wakeup container to label).
//
// Unlike the nginx generator nothing is installed or reloaded: Caddy picks the
// config up itself (caddy-docker-proxy watches labels and re-reads its base
// Caddyfile; a host install needs `caddy reload`).

const args = process.argv.slice(2);
const caddyfileOnly = args.includes("--caddyfile-only");
const positional = args.filter((a) => !a.startsWith("--"));
const configPath = path.resolve(positional[0] ?? path.join(__dirname, "../config.json"));
const outputDir = __dirname;
const caddyfilePath = path.join(outputDir, "Caddyfile");
const composePath = path.join(outputDir, "../docker-compose.override.yml");

if (!fs.existsSync(configPath)) {
  console.error(`${configPath} not found.`);
  process.exit(1);
}

interface ServiceConfig {
  route: string;
  target: string;
  type?: "http" | "tcp";
}

interface Config {
  proxyPort?: number;
  domain?: string;
  // Address Caddy uses to reach the wake proxy. Defaults to
  // host.docker.internal:<proxyPort>, which is what a caddy-docker-proxy
  // container needs (with extra_hosts: host.docker.internal:host-gateway).
  // Use 127.0.0.1:<proxyPort> for a Caddy running directly on the host.
  caddyUpstream?: string;
  services: ServiceConfig[];
}

const config: Config = JSON.parse(fs.readFileSync(configPath, "utf8"));

if (!config.domain) {
  console.error('No "domain" set in config.json — add e.g. "domain": "example.com" and re-run.');
  process.exit(1);
}
const domain: string = config.domain;
const proxyPort: number = config.proxyPort || 8080;
const upstream: string = config.caddyUpstream || `host.docker.internal:${proxyPort}`;

// Markers that let users keep hand edits across regenerations (same scheme
// as the nginx generator):
// - a file containing MANUAL_MARKER anywhere is never touched
// - lines between CUSTOM_START and CUSTOM_END are carried over into the
//   regenerated file. In the Caddyfile every site block has its own pair;
//   the compose file has one pair inside `labels:`.
const MANUAL_MARKER = "# wakeup:manual";
const CUSTOM_START = "# custom-start";
const CUSTOM_END = "# custom-end";
// First line of every file this generator writes — used to tell our own
// docker-compose.override.yml apart from one the user wrote themselves
const GENERATED_HEADER = "# Generated by DockerWakeUp (caddy-generator)";

/** Lines between the first CUSTOM_START/CUSTOM_END pair in `text`. */
function extractCustomLines(text: string): string[] {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => l.includes(CUSTOM_START));
  const end = lines.findIndex((l) => l.includes(CUSTOM_END));
  if (start === -1 || end === -1 || end <= start) return [];
  return lines.slice(start + 1, end);
}

/**
 * Custom lines per site block of an existing Caddyfile, keyed by the site
 * address (the text before the opening brace, e.g. "photos.example.com").
 */
function extractCaddyfileCustomLines(text: string): Map<string, string[]> {
  const result = new Map<string, string[]>();
  let site: string | null = null;
  let collecting: string[] | null = null;
  for (const line of text.split("\n")) {
    const siteMatch = line.match(/^([^\s#{][^{]*?)\s*\{\s*$/);
    if (siteMatch) {
      site = siteMatch[1].trim();
      continue;
    }
    if (collecting) {
      if (line.includes(CUSTOM_END)) {
        if (site && collecting.length > 0) result.set(site, collecting);
        collecting = null;
      } else {
        collecting.push(line);
      }
    } else if (line.includes(CUSTOM_START)) {
      collecting = [];
    }
  }
  return result;
}

const httpServices = config.services.filter((svc) => {
  // Raw TCP services (game servers etc.) are proxied directly by the wake
  // proxy's TCP listener — Caddy is not involved
  if (svc.type === "tcp") {
    console.log(`Skipped ${svc.route}: type "tcp" services don't use an HTTP Caddy config`);
    return false;
  }
  return true;
});

// ---------------------------------------------------------------------------
// Caddyfile
// ---------------------------------------------------------------------------

let existingCaddyfile = "";
if (fs.existsSync(caddyfilePath)) {
  existingCaddyfile = fs.readFileSync(caddyfilePath, "utf8");
}

if (existingCaddyfile.includes(MANUAL_MARKER)) {
  console.log(`Kept as-is (${MANUAL_MARKER}): ${caddyfilePath}`);
} else {
  const customBySite = extractCaddyfileCustomLines(existingCaddyfile);

  const blocks = httpServices.map((svc) => {
    const fullDomain = `${svc.route}.${domain}`;
    const customLines = customBySite.get(fullDomain) ?? [];
    if (customLines.length > 0) {
      console.log(`Preserving ${customLines.length} custom line(s) for ${fullDomain}`);
    }
    const customBlock = customLines.length > 0 ? customLines.join("\n") + "\n" : "";
    return `
${fullDomain} {
\t${CUSTOM_START} (lines between these markers survive regeneration)
${customBlock}\t${CUSTOM_END}

\t# Every request becomes /proxy/${svc.route}/... on the wake proxy. Caddy adds
\t# X-Forwarded-For/-Proto/-Host and passes WebSockets and SSE through as-is.
\trewrite * /proxy/${svc.route}{uri}
\treverse_proxy ${upstream}
}`.trimStart();
  });

  const caddyfile =
    `${GENERATED_HEADER} from ${path.basename(configPath)} — re-running the\n` +
    `# generator overwrites this file except for the custom-start/custom-end regions.\n` +
    `# Add a comment line saying wakeup:manual to take the file out of the generator's hands.\n` +
    `#\n` +
    `# Plain Caddy:          import ${caddyfilePath}\n` +
    `# caddy-docker-proxy:   mount this file and set CADDY_DOCKER_CADDYFILE_PATH to it\n` +
    `\n` +
    blocks.join("\n\n") +
    "\n";

  fs.writeFileSync(caddyfilePath, caddyfile);
  console.log(`Generated: ${caddyfilePath} (${blocks.length} site block(s))`);
}

// ---------------------------------------------------------------------------
// docker-compose override with caddy-docker-proxy labels
// ---------------------------------------------------------------------------

if (caddyfileOnly) {
  console.log("Skipped docker-compose.override.yml (--caddyfile-only)");
} else {
  // YAML double-quoted scalars accept JSON string escaping
  const yamlStr = (s: string) => JSON.stringify(s);

  let existingCompose = "";
  if (fs.existsSync(composePath)) {
    existingCompose = fs.readFileSync(composePath, "utf8");
  }

  // caddy-docker-proxy only accepts numeric suffixes (caddy_0, caddy_1, ...),
  // so the index follows the order of services in config.json
  const labelLines = httpServices.map((svc, i) => {
    const fullDomain = `${svc.route}.${domain}`;
    return [
      `      caddy_${i}: ${yamlStr(fullDomain)}`,
      `      caddy_${i}.rewrite: ${yamlStr(`* /proxy/${svc.route}{uri}`)}`,
      `      caddy_${i}.reverse_proxy: ${yamlStr(upstream)}`,
    ].join("\n");
  });
  const labelsBlock = labelLines.length > 0 ? labelLines.join("\n") + "\n" : "      {}\n";

  if (existingCompose.includes(MANUAL_MARKER)) {
    console.log(`Kept as-is (${MANUAL_MARKER}): ${composePath}`);
  } else if (existingCompose.length > 0 && !existingCompose.startsWith(GENERATED_HEADER)) {
    // The user has their own override (e.g. different volume mounts) — never
    // clobber it. Show what to merge instead.
    console.warn(
      `\n${composePath} exists and was not written by this generator — left untouched.\n` +
      `Add these labels to its docker-wakeup service yourself:\n\n` +
      `services:\n  docker-wakeup:\n    labels:\n${labelsBlock}`
    );
  } else {
    const customLines = extractCustomLines(existingCompose);
    if (customLines.length > 0) {
      console.log(`Preserving ${customLines.length} custom label line(s) in ${path.basename(composePath)}`);
    }
    const customBlock = customLines.length > 0 ? customLines.join("\n") + "\n" : "";

    const compose =
      `${GENERATED_HEADER} from ${path.basename(configPath)} — re-running the\n` +
      `# generator overwrites this file except for the custom-start/custom-end region.\n` +
      `# Add a comment line saying wakeup:manual to take the file out of the generator's hands.\n` +
      `#\n` +
      `# Adds caddy-docker-proxy labels to the docker-wakeup container. Docker Compose\n` +
      `# loads this override automatically next to docker-compose.yml, so a plain\n` +
      `#\n` +
      `#   docker compose up -d --build\n` +
      `#\n` +
      `# includes the labels. The labels point Caddy at ${upstream}; the Caddy\n` +
      `# container must be able to reach the wake proxy on the host (see\n` +
      `# examples/caddy-docker-proxy.yml). Not using Caddy? Just delete this file.\n` +
      `services:\n` +
      `  docker-wakeup:\n` +
      `    labels:\n` +
      `      ${CUSTOM_START} (lines between these markers survive regeneration)\n` +
      customBlock +
      `      ${CUSTOM_END}\n` +
      labelsBlock;

    fs.writeFileSync(composePath, compose);
    console.log(`Generated: ${composePath} (${labelLines.length} site(s))`);
  }
}

console.log(
  `\nUpstream for Caddy: ${upstream}` +
  (config.caddyUpstream ? "" : ` (default — set "caddyUpstream" in config.json to change)`)
);
