import fs from "fs";
import path from "path";
import { execSync } from "child_process";

// Generates reverse proxy configuration for the HTTP services in config.json.
// The wake proxy routes by hostname, so every output is a plain pass-through —
// no path rewriting anywhere.
//
//   --proxy nginx   confs/<route>.conf per service, symlinked into
//                   /etc/nginx/sites-enabled and NGINX reloaded (when present)
//   --proxy caddy   Caddyfile (plain Caddy `import`s it; caddy-docker-proxy
//                   mounts it via CADDY_DOCKER_CADDYFILE_PATH) and
//                   ../docker-compose.override.yml (caddy-docker-proxy labels
//                   on the docker-wakeup container, auto-loaded by compose)
//   --proxy traefik traefik-dynamic.yml for Traefik's file provider (point
//                   providers.file at it with watch: true)
//
// Usage: npm run nginx | npm run caddy | npm run traefik  [-- /path/to/config.json] [--caddyfile-only]
//    or: docker compose run --rm caddy-generator   (no Node.js on the host)
//
// --caddyfile-only skips docker-compose.override.yml (used by setup-service.sh:
// SystemD/PM2 deployments have no docker-wakeup container to label).

// ---------------------------------------------------------------------------
// CLI + config
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
let proxy = "";
const positional: string[] = [];
let caddyfileOnly = false;
for (let i = 0; i < args.length; i++) {
  if (args[i] === "--proxy") proxy = args[++i] ?? "";
  else if (args[i].startsWith("--proxy=")) proxy = args[i].slice("--proxy=".length);
  else if (args[i] === "--caddyfile-only") caddyfileOnly = true;
  else if (!args[i].startsWith("--")) positional.push(args[i]);
}
if (proxy !== "nginx" && proxy !== "caddy" && proxy !== "traefik") {
  console.error('Usage: generate.ts --proxy nginx|caddy|traefik [/path/to/config.json] [--caddyfile-only]');
  process.exit(1);
}

const configPath = path.resolve(positional[0] ?? path.join(__dirname, "../config.json"));
if (!fs.existsSync(configPath)) {
  console.error(`${configPath} not found.`);
  process.exit(1);
}

interface ServiceConfig {
  route: string;
  target: string;
  type?: "http" | "tcp";
  domains?: string[];   // extra hostnames the wake proxy also answers for
}

interface Config {
  proxyPort?: number;
  domain?: string;
  // Address Caddy uses to reach the wake proxy. Defaults to
  // host.docker.internal:<proxyPort> (what a caddy-docker-proxy container
  // needs). Use 127.0.0.1:<proxyPort> for a Caddy running directly on the host.
  caddyUpstream?: string;
  // Traefik equivalents: upstream the router points at, the entrypoint name,
  // and (optionally) a certresolver for the routers' tls block. Without a
  // resolver no tls key is emitted — enable TLS at the entrypoint instead
  // (like examples/traefik.yml) or set traefikCertResolver.
  traefikUpstream?: string;
  traefikEntrypoint?: string;
  traefikCertResolver?: string;
  services: ServiceConfig[];
}

const config: Config = JSON.parse(fs.readFileSync(configPath, "utf8"));
if (!config.domain) {
  console.error('No "domain" set in config.json — add e.g. "domain": "example.com" and re-run.');
  process.exit(1);
}
const domain: string = config.domain;
const proxyPort: number = config.proxyPort || 8080;

const httpServices = config.services.filter((svc) => {
  // Raw TCP services (game servers etc.) are proxied directly by the wake
  // proxy's TCP listener — no HTTP reverse proxy config applies
  if (svc.type === "tcp") {
    console.log(`Skipped ${svc.route}: type "tcp" services don't use an HTTP reverse proxy config`);
    return false;
  }
  return true;
});

/** All hostnames that should reach this service. */
const hostsFor = (svc: ServiceConfig): string[] =>
  [`${svc.route}.${domain}`, ...(svc.domains ?? [])];

// ---------------------------------------------------------------------------
// Markers that let users keep hand edits across regenerations:
// - a file containing MANUAL_MARKER anywhere is never touched
// - lines between CUSTOM_START and CUSTOM_END are carried over into the
//   regenerated file (e.g. auth_basic, extra headers, rate limits)
// ---------------------------------------------------------------------------
const MANUAL_MARKER = "# wakeup:manual";
const CUSTOM_START = "# custom-start";
const CUSTOM_END = "# custom-end";
// First line of every file this generator writes — tells our own
// docker-compose.override.yml apart from one the user wrote themselves
const GENERATED_HEADER = "# Generated by DockerWakeUp (proxy-generator)";

/** Lines between the first CUSTOM_START/CUSTOM_END pair in `text`. */
function extractCustomLines(text: string): string[] {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => l.includes(CUSTOM_START));
  const end = lines.findIndex((l) => l.includes(CUSTOM_END));
  if (start === -1 || end === -1 || end <= start) return [];
  return lines.slice(start + 1, end);
}

// ---------------------------------------------------------------------------
// NGINX
// ---------------------------------------------------------------------------

function generateNginx(): void {
  const outputDir = path.join(__dirname, "./confs");
  // NGINX_SITES_DIR overrides the symlink target for tests or non-standard
  // layouts; the nginx -t / reload step only runs for the standard location.
  const targetDir = process.env.NGINX_SITES_DIR || "/etc/nginx/sites-enabled";
  const isStandardTarget = !process.env.NGINX_SITES_DIR;

  // Privileged operations use sudo explicitly (and only when the target isn't
  // writable) so generated conf files stay owned by the user, not root
  const targetWritable = (() => { try { fs.accessSync(targetDir, fs.constants.W_OK); return true; } catch { return false; } })();
  const sudo = (typeof process.getuid === "function" && process.getuid() === 0) || targetWritable ? "" : "sudo ";
  const shellQuote = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;

  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  // One-time migration from the pre-merge layout: carry existing confs (and
  // their custom-marker edits / .htpasswd files) over from nginx-generator/
  const legacyDir = path.join(__dirname, "../nginx-generator/confs");
  const haveConfs = fs.readdirSync(outputDir).some((f) => f.endsWith(".conf") && f !== "example.conf");
  if (!haveConfs && fs.existsSync(legacyDir)) {
    for (const file of fs.readdirSync(legacyDir)) {
      if (file === "example.conf") continue;
      fs.copyFileSync(path.join(legacyDir, file), path.join(outputDir, file));
      console.log(`Migrated from nginx-generator/confs: ${file}`);
    }
  }

  const sitesEnabledExists = fs.existsSync(targetDir);
  if (!sitesEnabledExists) {
    console.warn(`${targetDir} not found — skipping symlink installation and NGINX reload.`);
    console.warn(`Copy the generated confs from ${outputDir} into your NGINX setup manually.`);
  }

  // Clean up broken symlinks in targetDir
  if (sitesEnabledExists) {
    for (const file of fs.readdirSync(targetDir)) {
      const dest = path.join(targetDir, file);
      try {
        if (fs.lstatSync(dest).isSymbolicLink()) {
          const target = fs.readlinkSync(dest);
          if (!fs.existsSync(target)) {
            execSync(`${sudo}rm -- ${shellQuote(dest)}`);
            console.log(`Removed broken symlink: ${dest}`);
          }
        }
      } catch {
        // ignore
      }
    }
  }

  for (const svc of httpServices) {
    const outputPath = path.join(outputDir, `${svc.route}.conf`);

    let customLines: string[] = [];
    if (fs.existsSync(outputPath)) {
      const existing = fs.readFileSync(outputPath, "utf8");
      if (existing.includes(MANUAL_MARKER)) {
        console.log(`Kept as-is (${MANUAL_MARKER}): ${outputPath}`);
        continue;
      }
      customLines = extractCustomLines(existing);
      if (customLines.length > 0) {
        console.log(`Preserving ${customLines.length} custom line(s) in ${svc.route}.conf`);
      }
    }

    const customBlock = customLines.length > 0 ? customLines.join("\n") + "\n" : "";
    const nginxConf = `
server {
    listen 80;
    server_name ${hostsFor(svc).join(" ")};

    location / {
        ${CUSTOM_START} (lines between these markers survive regeneration)
${customBlock}        ${CUSTOM_END}

        # The wake proxy routes by hostname — pass the request through untouched
        proxy_pass http://127.0.0.1:${proxyPort};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # https on purpose: TLS is terminated in front of this vhost (443
        # server block or a tunnel), and apps should generate https URLs
        proxy_set_header X-Forwarded-Proto https;
        proxy_http_version 1.1;
        # WebSocket support: pass the upgrade handshake through to the wake proxy
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_read_timeout 3600s;
        proxy_buffering off;
        proxy_request_buffering off;
    }
}`.trim();

    try {
      fs.writeFileSync(outputPath, nginxConf + "\n");
      console.log(`Generated: ${outputPath}`);
    } catch (e: any) {
      console.error(
        `Failed to write ${outputPath}: ${e?.message ?? e}\n` +
        `  (If it's owned by root from an older version, fix with: sudo chown $USER ${outputPath})`
      );
    }
  }

  if (!sitesEnabledExists) return;

  // Safely create symlinks in /etc/nginx/sites-enabled
  fs.readdirSync(outputDir).forEach((file) => {
    if (file === "example.conf") return; // documentation only
    if (!file.endsWith(".conf")) return;
    const src = path.join(outputDir, file);
    const dest = path.join(targetDir, file);
    try {
      if (fs.existsSync(dest)) {
        const stat = fs.lstatSync(dest);
        if (stat.isSymbolicLink() && fs.readlinkSync(dest) === src) {
          return; // Correct symlink already exists
        }
        execSync(`${sudo}rm -- ${shellQuote(dest)}`); // Wrong symlink or regular file
      }
      execSync(`${sudo}ln -s -- ${shellQuote(src)} ${shellQuote(dest)}`);
      console.log(`Symlinked: ${dest} → ${src}`);
    } catch (e) {
      console.error(`Failed to link ${file}:`, e);
    }
  });

  if (!isStandardTarget) {
    console.log(`\nSymlinked into ${targetDir} (custom NGINX_SITES_DIR) — reload NGINX yourself.`);
    return;
  }
  try {
    console.log("\nValidating NGINX config...");
    execSync(`${sudo}nginx -t`, { stdio: "inherit" });
    console.log("Reloading NGINX...");
    execSync(`${sudo}systemctl reload nginx`, { stdio: "inherit" });
    console.log("NGINX reloaded successfully!");
  } catch (error) {
    console.error("NGINX reload failed. Check the configuration above.");
    process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// Caddy / caddy-docker-proxy
// ---------------------------------------------------------------------------

/**
 * Custom lines per site block of an existing Caddyfile, keyed by the site
 * address line (e.g. "photos.example.com").
 */
function extractCaddyfileCustomLines(text: string): Map<string, string[]> {
  const result = new Map<string, string[]>();
  let site: string | null = null;
  let collecting: string[] | null = null;
  for (const line of text.split("\n")) {
    const siteMatch = line.match(/^([^\s#{][^{]*?)\s*\{\s*$/);
    if (siteMatch) {
      site = siteMatch[1].trim();
      continue;
    }
    if (collecting) {
      if (line.includes(CUSTOM_END)) {
        if (site && collecting.length > 0) result.set(site, collecting);
        collecting = null;
      } else {
        collecting.push(line);
      }
    } else if (line.includes(CUSTOM_START)) {
      collecting = [];
    }
  }
  return result;
}

function generateCaddy(): void {
  const caddyfilePath = path.join(__dirname, "Caddyfile");
  const composePath = path.join(__dirname, "../docker-compose.override.yml");
  const upstream: string = config.caddyUpstream || `host.docker.internal:${proxyPort}`;
  // YAML double-quoted scalars accept JSON string escaping
  const yamlStr = (s: string) => JSON.stringify(s);

  // ----- Caddyfile -----
  let existingCaddyfile = "";
  if (fs.existsSync(caddyfilePath)) existingCaddyfile = fs.readFileSync(caddyfilePath, "utf8");

  if (existingCaddyfile.includes(MANUAL_MARKER)) {
    console.log(`Kept as-is (${MANUAL_MARKER}): ${caddyfilePath}`);
  } else {
    const customBySite = extractCaddyfileCustomLines(existingCaddyfile);
    const blocks = httpServices.map((svc) => {
      const address = hostsFor(svc).join(", ");
      const customLines = customBySite.get(address) ?? [];
      if (customLines.length > 0) {
        console.log(`Preserving ${customLines.length} custom line(s) for ${address}`);
      }
      const customBlock = customLines.length > 0 ? customLines.join("\n") + "\n" : "";
      return `
${address} {
\t${CUSTOM_START} (lines between these markers survive regeneration)
${customBlock}\t${CUSTOM_END}

\t# The wake proxy routes by hostname; Caddy adds X-Forwarded-For/-Proto/-Host
\t# and passes WebSockets and SSE through as-is.
\treverse_proxy ${upstream}
}`.trimStart();
    });

    const caddyfile =
      `${GENERATED_HEADER} from ${path.basename(configPath)} — re-running the\n` +
      `# generator overwrites this file except for the custom-start/custom-end regions.\n` +
      `# Add a comment line saying wakeup:manual to take the file out of the generator's hands.\n` +
      `#\n` +
      `# Plain Caddy:          import ${caddyfilePath}\n` +
      `# caddy-docker-proxy:   mount this file and set CADDY_DOCKER_CADDYFILE_PATH to it\n` +
      `\n` +
      blocks.join("\n\n") +
      "\n";

    fs.writeFileSync(caddyfilePath, caddyfile);
    console.log(`Generated: ${caddyfilePath} (${blocks.length} site block(s))`);
  }

  // ----- docker-compose override with caddy-docker-proxy labels -----
  if (caddyfileOnly) {
    console.log("Skipped docker-compose.override.yml (--caddyfile-only)");
  } else {
    // caddy-docker-proxy only accepts numeric suffixes (caddy_0, caddy_1, ...),
    // so the index follows the order of services in config.json
    const labelLines = httpServices.map((svc, i) => [
      `      caddy_${i}: ${yamlStr(hostsFor(svc).join(" "))}`,
      `      caddy_${i}.reverse_proxy: ${yamlStr(upstream)}`,
    ].join("\n"));
    const labelsBlock = labelLines.length > 0 ? labelLines.join("\n") + "\n" : "      {}\n";

    let existingCompose = "";
    if (fs.existsSync(composePath)) existingCompose = fs.readFileSync(composePath, "utf8");

    if (existingCompose.includes(MANUAL_MARKER)) {
      console.log(`Kept as-is (${MANUAL_MARKER}): ${composePath}`);
    } else if (existingCompose.length > 0 && !existingCompose.startsWith(GENERATED_HEADER)) {
      // The user has their own override (e.g. different volume mounts) — never
      // clobber it. Show what to merge instead.
      console.warn(
        `\n${composePath} exists and was not written by this generator — left untouched.\n` +
        `Add these labels to its docker-wakeup service yourself:\n\n` +
        `services:\n  docker-wakeup:\n    labels:\n${labelsBlock}`
      );
    } else {
      const customLines = extractCustomLines(existingCompose);
      if (customLines.length > 0) {
        console.log(`Preserving ${customLines.length} custom label line(s) in ${path.basename(composePath)}`);
      }
      const customBlock = customLines.length > 0 ? customLines.join("\n") + "\n" : "";

      const compose =
        `${GENERATED_HEADER} from ${path.basename(configPath)} — re-running the\n` +
        `# generator overwrites this file except for the custom-start/custom-end region.\n` +
        `# Add a comment line saying wakeup:manual to take the file out of the generator's hands.\n` +
        `#\n` +
        `# Adds caddy-docker-proxy labels to the docker-wakeup container. Docker Compose\n` +
        `# loads this override automatically next to docker-compose.yml, so a plain\n` +
        `#\n` +
        `#   docker compose up -d --build\n` +
        `#\n` +
        `# includes the labels. The labels point Caddy at ${upstream}; the Caddy\n` +
        `# container must be able to reach the wake proxy on the host (see\n` +
        `# examples/caddy-docker-proxy.yml). Not using Caddy? Just delete this file.\n` +
        `services:\n` +
        `  docker-wakeup:\n` +
        `    labels:\n` +
        `      ${CUSTOM_START} (lines between these markers survive regeneration)\n` +
        customBlock +
        `      ${CUSTOM_END}\n` +
        labelsBlock;

      fs.writeFileSync(composePath, compose);
      console.log(`Generated: ${composePath} (${labelLines.length} site(s))`);
    }
  }

  console.log(
    `\nUpstream for Caddy: ${upstream}` +
    (config.caddyUpstream ? "" : ` (default — set "caddyUpstream" in config.json to change)`)
  );
}

// ---------------------------------------------------------------------------
// Traefik (file provider)
// ---------------------------------------------------------------------------

function generateTraefik(): void {
  const outPath = path.join(__dirname, "traefik-dynamic.yml");
  const upstream: string = config.traefikUpstream || `host.docker.internal:${proxyPort}`;
  const entrypoint: string = config.traefikEntrypoint || "websecure";
  const resolver: string | undefined = config.traefikCertResolver;
  const BT = "`"; // backtick, used inside Traefik rule expressions

  if (fs.existsSync(outPath) && fs.readFileSync(outPath, "utf8").includes(MANUAL_MARKER)) {
    console.log(`Kept as-is (${MANUAL_MARKER}): ${outPath}`);
    return;
  }

  const tlsBlock = resolver
    ? `      tls: { certResolver: ${JSON.stringify(resolver)} }\n`
    : `      # TLS comes from the entrypoint (examples/traefik.yml enables it there);\n` +
      `      # or set "traefikCertResolver" in config.json to add one per router\n`;

  // One catch-all router covers every <route>.<domain>; services with extra
  // `domains` get their own router, since aliases don't match the regexp
  const escapedDomain = domain.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const routers: string[] = [];
  routers.push(
    `    docker-wakeup:\n` +
    `      rule: HostRegexp(${BT}^.+\\.${escapedDomain}$${BT})\n` +
    `      entryPoints: [${JSON.stringify(entrypoint)}]\n` +
    tlsBlock +
    `      service: docker-wakeup\n`
  );
  for (const svc of httpServices) {
    const aliases = svc.domains ?? [];
    if (aliases.length === 0) continue;
    const rule = aliases.map((d) => `Host(${BT}${d}${BT})`).join(" || ");
    routers.push(
      `    docker-wakeup-${svc.route}-aliases:\n` +
      `      rule: ${rule}\n` +
      `      entryPoints: [${JSON.stringify(entrypoint)}]\n` +
      tlsBlock +
      `      service: docker-wakeup\n`
    );
  }

  const out =
    `${GENERATED_HEADER} from ${path.basename(configPath)} — re-running the\n` +
    `# generator overwrites this file. Add a comment line saying wakeup:manual to\n` +
    `# take it out of the generator's hands.\n` +
    `#\n` +
    `# Dynamic configuration for Traefik's file provider. Point Traefik at it:\n` +
    `#   --providers.file.filename=/etc/traefik/docker-wakeup.yml\n` +
    `#   --providers.file.watch=true\n` +
    `# (mount this file there — see examples/traefik.yml for a complete stack.)\n` +
    `# The wake proxy routes by hostname, so this file only changes when the\n` +
    `# domain or per-service domains aliases change.\n` +
    `http:\n` +
    `  routers:\n` +
    routers.join("") +
    `  services:\n` +
    `    docker-wakeup:\n` +
    `      loadBalancer:\n` +
    `        servers:\n` +
    `          - url: ${JSON.stringify(`http://${upstream}`)}\n`;

  fs.writeFileSync(outPath, out);
  console.log(`Generated: ${outPath} (catch-all *.${domain}` +
    (routers.length > 1 ? ` + ${routers.length - 1} alias router(s)` : "") + `)`);
  console.log(
    `\nUpstream for Traefik: http://${upstream}` +
    (config.traefikUpstream ? "" : ` (default — set "traefikUpstream" in config.json to change)`)
  );
}

if (proxy === "nginx") generateNginx();
else if (proxy === "traefik") generateTraefik();
else generateCaddy();
