// Markers that let users keep hand edits across regenerations:
// - a file containing MANUAL_MARKER anywhere is never touched
// - lines between CUSTOM_START and CUSTOM_END are carried over into the
//   regenerated file (e.g. auth_basic, extra headers, rate limits)

/** A file containing this anywhere is left alone by every generator. */
export const MANUAL_MARKER = "# wakeup:manual";
/** Opens the region whose lines survive regeneration. */
export const CUSTOM_START = "# custom-start";
/** Closes that region. */
export const CUSTOM_END = "# custom-end";
/**
 * First line of every file this generator writes — tells our own
 * docker-compose.override.yml apart from one the user wrote themselves.
 */
export const GENERATED_HEADER = "# Generated by DockerWakeUp (proxy-generator)";

/** Lines between the first CUSTOM_START/CUSTOM_END pair in `text`. */
export function extractCustomLines(text: string): string[] {
  const lines = text.split("\n");
  const start = lines.findIndex((l) => l.includes(CUSTOM_START));
  const end = lines.findIndex((l) => l.includes(CUSTOM_END));
  if (start === -1 || end === -1 || end <= start) return [];
  return lines.slice(start + 1, end);
}

/**
 * Custom lines per site block of an existing Caddyfile, keyed by the site
 * address line (e.g. "photos.example.com").
 */
export function extractCaddyfileCustomLines(text: string): Map<string, string[]> {
  const result = new Map<string, string[]>();
  let site: string | null = null;
  let collecting: string[] | null = null;
  for (const line of text.split("\n")) {
    const siteMatch = line.match(/^([^\s#{][^{]*?)\s*\{\s*$/);
    if (siteMatch) {
      site = siteMatch[1].trim();
      continue;
    }
    if (collecting) {
      if (line.includes(CUSTOM_END)) {
        if (site && collecting.length > 0) result.set(site, collecting);
        collecting = null;
      } else {
        collecting.push(line);
      }
    } else if (line.includes(CUSTOM_START)) {
      collecting = [];
    }
  }
  return result;
}
